# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.3.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-test-sonar:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    parameters:
      max-tries:
        default: 1
        description: Max number of tries. To disable retries, set this to 1.
        type: integer
    executor:
      name: android/android-machine
      tag: 2021.10.1

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          command:
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            echo "export JAVA_HOME=/usr/lib/jvm/java-${PARAM_JAVA_VER}-openjdk-amd64" >> ~/.bashrc
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc

      # Checkout the code as the first step.
      - checkout

        # Restore saved gradle cache if exist
      - android/restore-gradle-cache

      # The next step will run the unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      # save cache for saving build time
      - android/save-gradle-cache

      - store_test_results:
          path: app/build/test-results

      # And finally run the debug build
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk

      - run:
          name: SonarCloud analysis
          command: ./gradlew sonar

workflows:
  main-workflow:
    jobs:
      - build-test-sonar



